apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scalingdeploys.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentName:
                  type: string
                replicamax:
                  type: integer
                replicamin:
                  type: integer
  scope: Namespaced
  names:
    plural: scalingdeploys
    singular: scalingdeploy
    kind: ScalingDeploy
    shortNames:
    - sdeploy
